server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jackdang
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  data:
    web:
    pageable:
      default-page-size: 10
      max-page-size: 2000

jwt:
  secretKey : jackdang-secret-key

logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace